namespace i3D
{
    /// <summary>
    /// Enumeration of all the errors that can be returned by the SDK.
    /// </summary>
    public enum I3dError
    {
        None = 0,
        ValidationCallbackIsNullptr = 100,
        ValidationCountryIsNullptr = 101,
        ValidationDcLocationNameIsNullptr = 102,
        ValidationCallIpV4IsNullptr = 103,
        ValidationIpV6IsNullptr = 104,
        ValidationJsonIsNullptr = 105,
        ValidationSitesGetterIsNullptr = 106,
        ValidationPingersIsNullptr = 107,
        ValidationStatusIsNullptr = 108,
        ValidationSizeIsNullptr = 109,
        ValidationContinentIdIsNullptr = 110,
        ValidationDcLocationIdIsNullptr = 111,
        ValidationIpIsNullptr = 112,
        ValidationLastTimeIsNullptr = 113,
        ValidationAverageTimeIsNullptr = 114,
        ValidationMinTimeIsNullptr = 115,
        ValidationMaxTimeIsNullptr = 116,
        ValidationMedianTimeIsNullptr = 117,
        ValidationPingResponseCountIsNullptr = 118,
        ValidationResultIsNullptr = 119,
        ValidationIpListIsNullptr = 120,
        ValidationHttpGetCallbackIsNullptr = 121,
        ValidationSizeIsTooSmall = 122,
        DataParseFailed = 200,
        DataJsonPayloadIsNullptr = 201,
        DataJsonServerInformationIsInvalid = 202,
        SitesGetterNotInitialized = 300,
        SitesGetterAlreadyInitialized = 301,
        SitesGetterCallbackIsNullptr = 302,
        SitesGetterAllocationFailed = 303,
        SitesGetterUnknownStatus = 304,
        SitesGetterHttpGetCallbackNotSet = 305,
        SitesGetterPosOutOfRange = 306,
        SitesGetterIpPosOutOfRange = 307,
        IpListPosIsOutOfRange = 400,
        IpListAllocationFailed = 401,
        SocketSystemInitFail = 500,
        SocketCreationFail = 501,
        SocketTtlSetSocketOptionFail = 502,
        SocketSystemCleanupFail = 503,
        SocketInvalidIpV4 = 504,
        SocketSendFail = 505,
        SocketReceiveBufferTooSmall = 506,
        SocketReceiveError = 507,
        SocketTooFewBytes = 508,
        SocketDestinationUnreachable = 509,
        SocketUnknownIcmpPacketType = 510,
        SocketTtlExpired = 511,
        SocketInvalidTime = 512,
        SocketAlreadyInitialized = 513,
        SocketNotInitialized = 514,
        SocketPingNotSent = 515,
        SocketUnknownStatus = 516,        
        SocketInvalidSequenceNumber = 517,
        SocketSelectFailed = 518,
        SocketNotReady = 519,
        SocketCannotBeReset = 520,
        PingerDivisionByZero = 600,
        PingerInvalidTime = 601,
        PingerAlreadyInitialized = 602,
        PingerIsUninitialized = 603,
        PingersNotInitialized = 700,
        PingersAlreadyInitialized = 701,
        PingersPosIsOutOfRange = 702
    }
}